### ISSUE TITLE
You can keep getting new letters

### ISSUE THREAD

**Issue by slowe** [rosswintle/static-word-game#14]
Once a player makes a play they are given new letters but that is before they share the link. So they can just reload the page and make the play again to get different replacement letters. They can do that until they get the letters they want for their next turn. Perhaps new letters should only be assigned on the other player's go? That way the player who is getting new letters can't game them.

**Comment by rosswintle** [comment]
Hmm. I used to assign letters when you opened a game link and had less than 7 in your rack. It was annoying because it was nice to immediately see the new letters and start thinking about a subsequent move.

The best fix here is to seed the random number generator with something like the game hash so that the "random" letters given are always the same.

I also note, in passing, that it's trivial to see the other player's tiles too (open the copied link!) so there's a certain amount of trust required here.

**Comment by rosswintle** [comment]
This issue with being able to get different letters should be fixed now!

Thanks for reporting it.
